/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminDepositRequest {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'userId' : UserId,
  'userPrincipal' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface AdminTournamentMatchUpdate {
  'matchId' : bigint,
  'matchInfo' : MatchInfo,
}
export interface AdminUpdateTournamentRequest {
  'matchTime' : [] | [Time],
  'status' : [] | [boolean],
  'matchCount' : [] | [bigint],
  'entryFee' : [] | [bigint],
}
export interface MatchInfo {
  'playerUID' : string,
  'matchTime' : Time,
  'whatsappNumber' : string,
}
export type Time = bigint;
export interface TournamentInfo {
  'matchTime' : Time,
  'status' : boolean,
  'matchCount' : bigint,
  'entryFee' : bigint,
}
export interface TournamentJoinRequest {
  'freeFireUid' : string,
  'joinTimestamp' : Time,
  'userId' : UserId,
  'whatsappNumber' : string,
  'entryFeePaid' : bigint,
  'userPrincipal' : Principal,
}
export type UserId = bigint;
export interface UserProfile {
  'userId' : UserId,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveDeposit' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deposit' : ActorMethod<[bigint], bigint>,
  'getAllTournamentJoinRequests' : ActorMethod<
    [],
    Array<TournamentJoinRequest>
  >,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getBalanceByPrincipalId' : ActorMethod<[Principal], bigint>,
  'getBalanceByUserId' : ActorMethod<[UserId], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntryFee' : ActorMethod<[], bigint>,
  'getPendingDepositRequests' : ActorMethod<[], Array<AdminDepositRequest>>,
  'getPendingTournaments' : ActorMethod<[], Array<MatchInfo>>,
  'getTotalBalance' : ActorMethod<[], bigint>,
  'getTournamentInfo' : ActorMethod<[], TournamentInfo>,
  'getUserBalance' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasOpenTournaments' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isTournamentEntryOpen' : ActorMethod<[], boolean>,
  'joinTournament' : ActorMethod<[string, string], undefined>,
  'rejectDeposit' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setEntryFee' : ActorMethod<[bigint], undefined>,
  'setMatch' : ActorMethod<[bigint, MatchInfo], undefined>,
  'setMatchCount' : ActorMethod<[bigint], undefined>,
  'setMatchTime' : ActorMethod<[Time], undefined>,
  'setTournamentEntryOpen' : ActorMethod<[boolean], undefined>,
  'updateMatch' : ActorMethod<[bigint, MatchInfo], undefined>,
  'updateMatchTime' : ActorMethod<[bigint, Time], undefined>,
  'updateTournament' : ActorMethod<
    [AdminUpdateTournamentRequest],
    TournamentInfo
  >,
  'updateTournamentMatches' : ActorMethod<
    [Array<AdminTournamentMatchUpdate>],
    Array<MatchInfo>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];