/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TournamentJoinRequest = IDL.Record({
  'freeFireUid' : IDL.Text,
  'joinTimestamp' : Time,
  'userId' : UserId,
  'whatsappNumber' : IDL.Text,
  'entryFeePaid' : IDL.Nat,
  'userPrincipal' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'userId' : UserId,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const DirectDeposit = IDL.Record({
  'userId' : UserId,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const AdminDepositRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'userId' : UserId,
  'userPrincipal' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const MatchInfo = IDL.Record({
  'playerUID' : IDL.Text,
  'matchTime' : Time,
  'whatsappNumber' : IDL.Text,
});
export const TournamentInfo = IDL.Record({
  'matchTime' : Time,
  'status' : IDL.Bool,
  'matchCount' : IDL.Nat,
  'entryFee' : IDL.Nat,
});
export const AdminUpdateTournamentRequest = IDL.Record({
  'matchTime' : IDL.Opt(Time),
  'status' : IDL.Opt(IDL.Bool),
  'matchCount' : IDL.Opt(IDL.Nat),
  'entryFee' : IDL.Opt(IDL.Nat),
});
export const AdminTournamentMatchUpdate = IDL.Record({
  'matchId' : IDL.Nat,
  'matchInfo' : MatchInfo,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminDirectDeposit' : IDL.Func([UserId, IDL.Nat], [], []),
  'adminDirectDepositByPrincipal' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'approveDeposit' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deposit' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getAllTournamentJoinRequests' : IDL.Func(
      [],
      [IDL.Vec(TournamentJoinRequest)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getBalanceByPrincipalId' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getBalanceByUserId' : IDL.Func([UserId], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDirectDepositHistory' : IDL.Func([], [IDL.Vec(DirectDeposit)], ['query']),
  'getEntryFee' : IDL.Func([], [IDL.Nat], ['query']),
  'getPendingDepositRequests' : IDL.Func(
      [],
      [IDL.Vec(AdminDepositRequest)],
      ['query'],
    ),
  'getPendingTournaments' : IDL.Func([], [IDL.Vec(MatchInfo)], ['query']),
  'getTotalBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getTournamentInfo' : IDL.Func([], [TournamentInfo], ['query']),
  'getUserBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasOpenTournaments' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isTournamentEntryOpen' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectDeposit' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setEntryFee' : IDL.Func([IDL.Nat], [], []),
  'setMatch' : IDL.Func([IDL.Nat, MatchInfo], [], []),
  'setMatchCount' : IDL.Func([IDL.Nat], [], []),
  'setMatchTime' : IDL.Func([Time], [], []),
  'setTournamentEntryOpen' : IDL.Func([IDL.Bool], [], []),
  'updateMatch' : IDL.Func([IDL.Nat, MatchInfo], [], []),
  'updateMatchTime' : IDL.Func([IDL.Nat, Time], [], []),
  'updateTournament' : IDL.Func(
      [AdminUpdateTournamentRequest],
      [TournamentInfo],
      [],
    ),
  'updateTournamentMatches' : IDL.Func(
      [IDL.Vec(AdminTournamentMatchUpdate)],
      [IDL.Vec(MatchInfo)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TournamentJoinRequest = IDL.Record({
    'freeFireUid' : IDL.Text,
    'joinTimestamp' : Time,
    'userId' : UserId,
    'whatsappNumber' : IDL.Text,
    'entryFeePaid' : IDL.Nat,
    'userPrincipal' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'userId' : UserId,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const DirectDeposit = IDL.Record({
    'userId' : UserId,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const AdminDepositRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'userId' : UserId,
    'userPrincipal' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const MatchInfo = IDL.Record({
    'playerUID' : IDL.Text,
    'matchTime' : Time,
    'whatsappNumber' : IDL.Text,
  });
  const TournamentInfo = IDL.Record({
    'matchTime' : Time,
    'status' : IDL.Bool,
    'matchCount' : IDL.Nat,
    'entryFee' : IDL.Nat,
  });
  const AdminUpdateTournamentRequest = IDL.Record({
    'matchTime' : IDL.Opt(Time),
    'status' : IDL.Opt(IDL.Bool),
    'matchCount' : IDL.Opt(IDL.Nat),
    'entryFee' : IDL.Opt(IDL.Nat),
  });
  const AdminTournamentMatchUpdate = IDL.Record({
    'matchId' : IDL.Nat,
    'matchInfo' : MatchInfo,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminDirectDeposit' : IDL.Func([UserId, IDL.Nat], [], []),
    'adminDirectDepositByPrincipal' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [],
        [],
      ),
    'approveDeposit' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deposit' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getAllTournamentJoinRequests' : IDL.Func(
        [],
        [IDL.Vec(TournamentJoinRequest)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getBalanceByPrincipalId' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getBalanceByUserId' : IDL.Func([UserId], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDirectDepositHistory' : IDL.Func(
        [],
        [IDL.Vec(DirectDeposit)],
        ['query'],
      ),
    'getEntryFee' : IDL.Func([], [IDL.Nat], ['query']),
    'getPendingDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(AdminDepositRequest)],
        ['query'],
      ),
    'getPendingTournaments' : IDL.Func([], [IDL.Vec(MatchInfo)], ['query']),
    'getTotalBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getTournamentInfo' : IDL.Func([], [TournamentInfo], ['query']),
    'getUserBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasOpenTournaments' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isTournamentEntryOpen' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectDeposit' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setEntryFee' : IDL.Func([IDL.Nat], [], []),
    'setMatch' : IDL.Func([IDL.Nat, MatchInfo], [], []),
    'setMatchCount' : IDL.Func([IDL.Nat], [], []),
    'setMatchTime' : IDL.Func([Time], [], []),
    'setTournamentEntryOpen' : IDL.Func([IDL.Bool], [], []),
    'updateMatch' : IDL.Func([IDL.Nat, MatchInfo], [], []),
    'updateMatchTime' : IDL.Func([IDL.Nat, Time], [], []),
    'updateTournament' : IDL.Func(
        [AdminUpdateTournamentRequest],
        [TournamentInfo],
        [],
      ),
    'updateTournamentMatches' : IDL.Func(
        [IDL.Vec(AdminTournamentMatchUpdate)],
        [IDL.Vec(MatchInfo)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };